import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import { SidebarComponent } from "@/components/layout/sideBar";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task system",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Shows navbar only if the user is logged
  const cookieStore = cookies();
  const tokenExists = cookieStore.get("tokenLogin")?.value;
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${inter.className} min-h-screen bg-gray-50`}>
        {tokenExists ? (
          <SidebarComponent>{children}</SidebarComponent>
        ) : (
          <>{children}</>
        )}
      </body>
    </html>
  );
}
