### Obtener todos usuarios
GET http://localhost:3000/api/user
Accept: application/json
Content-Type: application/json

### Registrar nuevo usuario
POST http://localhost:3000/api/auth/register/
Accept: application/json
Content-Type: application/json

{
    "username": "admin1",
    "password": "pass123",
    // Si no se envie role queda como Role.regular
    "role": "admin"
}

### Autenticar usuario
GET http://localhost:3000/api/auth/login
Accept: application/vnd.api+json
Authorization: Basic admin1 pass123
